version: '3.8'
name: wld
services:
  nginx:
    build: 
      context: ./config/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/certs:/etc/nginx/ssl/certs:ro
      - ./sites:/var/www/html
      - ./config/nginx/sites:/etc/nginx/conf.d
    depends_on:
      - mariadb
      - php
    networks:
      - wld-network

  php:
    build: 
      context: ./config/php
      args:
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
    container_name: php
    volumes:
      - ./sites:/var/www/html
    command: ["/bin/sh", "-c", "/wld/after-startup.sh"]
    links: 
      - mariadb
      - redis
    # env_file:
    #   - ./.env
    networks:
      - wld-network

  mariadb:
    container_name: mariadb
    build: 
      context: ./config/mariadb
      args:
        - MARIADB_VERSION=${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password123!}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-password123!}
      - MYSQL_ALLOWED_EMPTY_PASSWORD=${MYSQL_ALLOWED_EMPTY_PASSWORD:-no}
      - MARIADB_USER=${MARIADB_USER:-wpadmin}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-password123!}
    volumes:
      - wld_data:/var/lib/mysql
      # @TODO replace with site .cache
      - ./sites:/sites
    networks:
      - wld-network

  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass root
    networks:
      - wld-network

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - mariadb
    restart: always
    ports:
      - 8081:8080
    networks:
      - wld-network

volumes:
  wld_data:
  redis_data:

networks:
  wld-network:
    driver: bridge
