version: '3.8'
name: wld
services:
  nginx:
    image: nginx:${NGINX_VERSION:-stable-alpine}
    build: 
      context: ./config/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION:-stable-alpine}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/certs:/etc/nginx/ssl/certs:ro
      - ./sites:/var/www/html
    depends_on:
      - mariadb
      - php
    networks:
      - wld-network

  php:
    image: php:${PHP_FPM_VERSION:-8.3-fpm-alpine}
    build: 
      context: ./config/php
      args:
        - PHP_FPM_VERSION=${PHP_FPM_VERSION:-8.3-fpm-alpine}
    container_name: php
    volumes:
      - ./sites:/var/www/html
    networks:
      - wld-network

  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.5}
    container_name: mariadb
    build: 
      context: ./config/mariadb
      args:
        - MARIADB_VERSION=${MARIADB_VERSION:-10.5}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password123!}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-password123!}
      - MYSQL_ALLOWED_EMPTY_PASSWORD=${MYSQL_ALLOWED_EMPTY_PASSWORD:-no}
      - MARIADB_USER=wpadmin
      - MARIADB_PASSWORD=password123!
    volumes:
      - wld_data:/var/lib/mysql
      - ./sites:/path/to/sites
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - wld-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - wld-network

volumes:
  wld_data: {}

networks:
  wld-network:
    driver: bridge
