version: '3.8'

services:
  nginx:
    build: 
      context: ./config/nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/certs:/etc/nginx/ssl/certs:ro
      - ./sites:/var/www/html
    depends_on:
      - php-8
      - mariadb
    networks:
      - wp-network

  php-8:
    image: php:8.0-fpm
    container_name: php-8
    volumes:
      - ./sites:/var/www/html
    networks:
      - wp-network

  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password123!}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-password123!}
      - MYSQL_ALLOWED_EMPTY_PASSWORD=${MYSQL_ALLOWED_EMPTY_PASSWORD:-no}
      - MARIADB_USER=wpadmin
      - MARIADB_PASSWORD=password123!
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge
