#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Define function to call other scripts
call_script() {
    script_name="$1"
    # Assuming scripts are in the `scripts` directory
    script_path="${SCRIPT_PATH}/cli/${script_name}.sh"
    
    if [[ -f "$script_path" ]]; then
        bash "$script_path"
    else
        echo "Script does not exist: $script_name"
        exit 1
    fi
}

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --run|-r) call_script "$2"; shift ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done
